### ISSUE TITLE
Error opening FT files

### ISSUE THREAD

**Issue by algoravioli** [LukeEmmet/LuteScribe#1]
Hi, I'm facing an error opening .ft3 files, I have tried multiple ft3 files but they all seem to have an error. Am I doing something wrong (special way of importing?)?

**Comment by LukeEmmet** [comment]
It should open a majority of FT3 files, but some might not work correctly. For example this one from Sarge Gerborde's website opens fine for me:

https://www.lutemusic.org/composers/Dowland/solos/02_forlorne_hope_8C.ft3

see screenshot
![lutescribe](https://user-images.githubusercontent.com/6898220/164528064-0dd92ad2-e7e3-4719-8ab8-6165a1fa6176.jpg)

Does this file not open for you? What error is it showing?
